One Mold, Many Shapes
> inventory
   1.  Rusty sword       (wt 4.0, val 5)
   2.  Healing potion    (wt 0.5, val 12)
   3.  Iron key          (wt 0.1, val 0)
   4.  Loaf of bread     (wt 0.1, val 1)
   5.  Cloak of shadows  (wt 1.5, val 80)
> list
Bone Spider   HP 6   ATK 2   weakness: fire
Cave Troll   HP 28   ATK 7   weakness: fire
Cinder Bat   HP 4   ATK 1   weakness: water
Frostmaw   HP 22   ATK 6   weakness: fire
Goblin   HP 8   ATK 2   weakness: fire
Ironclaw Bear   HP 24   ATK 5   weakness: slashing
Lich   HP 35   ATK 6   weakness: holy
Marsh Lurker   HP 18   ATK 3   weakness: fire
Necrothrall   HP 16   ATK 4   weakness: light
Ratking   HP 9   ATK 2   weakness: fire
Shadow Hound   HP 12   ATK 4   weakness: light
Skeleton   HP 10   ATK 3   weakness: blunt
Stone Sentinel   HP 30   ATK 5   weakness: blunt
Wisp   HP 3   ATK 1   weakness: holy
Wraith   HP 14   ATK 4   weakness: holy
> search Goblin
Goblin   HP 8   ATK 2   weakness: fire
> search Iron key
  Iron key  (wt 0.1, val 0)
> inspect 3
  Iron key  (wt 0.1, val 0)
> inspect 99
No such item. (index 98 out of bounds for size 5)
> sort inventory by weight
   1.  Iron key          (wt 0.1, val 0)
   2.  Loaf of bread     (wt 0.1, val 1)
   3.  Healing potion    (wt 0.5, val 12)
   4.  Cloak of shadows  (wt 1.5, val 80)
   5.  Rusty sword       (wt 4.0, val 5)

>------ Build started: Project: CMakeLists, Configuration: Debug ------
  [1/2] Building CXX object CMakeFiles\the_descent.dir\main.cpp.obj
  FAILED: CMakeFiles/the_descent.dir/main.cpp.obj
  C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1444~1.352\bin\Hostx64\x64\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -std:c++17 -MDd /W4 /showIncludes /FoCMakeFiles\the_descent.dir\main.cpp.obj /FdCMakeFiles\the_descent.dir\ /FS -c C:\Users\karau\Documents\GitHub\comp2450\project\floor-03-starter\main.cpp
C:\Users\karau\Documents\GitHub\comp2450\project\floor-03-starter\main.cpp(46): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\karau\Documents\GitHub\comp2450\project\floor-03-starter\main.cpp(46): error C2440: 'initializing': cannot convert from 'initializer list' to 'int'
  C:\Users\karau\Documents\GitHub\comp2450\project\floor-03-starter\main.cpp(46): note: The initializer contains too many elements
C:\Users\karau\Documents\GitHub\comp2450\project\floor-03-starter\main.cpp(142): error C2872: 'findByName': ambiguous symbol
  C:\Users\karau\Documents\GitHub\comp2450\project\floor-03-starter\bestiary/Search.h(50): note: could be 'const T *dungeon::findByName(const dungeon::Bag<T> &,const std::string &)'
  C:\Users\karau\Documents\GitHub\comp2450\project\floor-03-starter\main.cpp(46): note: or       'int `anonymous-namespace'::findByName'
  ninja: build stopped: subcommand failed.

I only changed lines 45 and 46. It also marked 142 as an error because it also contains findByName and search.h because it also contains findByName
The main error is calling findByName without putting it in a variable.

> inspect 99
> inspect 3
  Iron key  (wt 0.1, val 0)
Calling inspect 99 just moves to the next line waiting for a response
The empty handler does not show as an error while not having one at least has a error we can see

A player would be able to break it if they called any n less than 1. Inventory can’t be negative size so this would cause a problem. Using [] can silently fail instead of throwing and giving us something to work with. Unless you tested every single case, which I know you didn’t, then there is no way to know based off of one or two tests. The only time that [] would be better is when we ensure they cannot enter anything less than 1 as n.

The catch in main wouldn’t hit a throw in bag exception and so when thrown there would be no error so when the player puts in inspect 99 it would stop working without giving a reason. The compiler technically says there’s no error. To fix this you’d have to make your own catch for bag exception or just do what we did cause it works. Every time you make a new exception though you would have to make a new catch